credentials:
  useSecret: true
  name: "velero-bucket-credentials"
configuration:
snapshotsEnabled: false
schedules:
  udsbackup:
    disabled: false
    schedule: "1 * * * *"
    useOwnerReferencesInBackup: false
    template:
      csiSnapshotTimeout: 0s
      includeClusterResources: true
      snapshotVolumes: false
      excludedNamespaces:
        - kube-system
        - velero
      ttl: "240h"
metrics:
  serviceMonitor:
    enabled: true